### ISSUE TITLE
Remove unused dependency

### ISSUE THREAD

**Issue by dy** [kwhitley/use-store#4]
Thanks for the easiest store implementation, it really changes the way react apps can be built.
I think there's redundant dependency that belongs to `devDependencies`: @testing-library/react

**Comment by dy** [comment]
(Also I wonder why is that not published as `use-store` npm package, since that's free)

**Comment by dy** [comment]
I see the commits thx!

**Comment by dy** [comment]
@kwhitley can you pls publish the package?

**Comment by kwhitley** [comment]
@dy glad to hear it's helping you!  We use it extensively at my office as well, and I use it throughout my own codebases... I agree, it's totally a game-changer, especially when you consider the optional persistence layer (not to mention broadcasting)!

Great suggestion on the library name... it's moved!  Currently [use-store-hook](https://www.npmjs.com/package/use-store-hook) will continue to work, but now includes a relocation notice warning with instructions to switch modules.  Mind verifying that the behavior is acceptable before migrating to the updated [use-store](https://www.npmjs.com/package/use-store)?

**Comment by dy** [comment]
Sure) Tbh I tried installing `use-store` yesterday already, that's great implementation and great name.

I stumbled upon an issue though with dynamic store keys.
```js
function Component () {
  let [type] = useStore(`type`)
  let [cart] = useStore(`cart-${type}`)
  // `cart` doesn't change here
}
```
That is rather react hooks case, but I wonder if that'd be possible to handle that. (can create a separate issue)
